name: Merge/Push to a base branch (develop/epics)
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          # token: ${{ secrets.GH_PAT }} # token not needed for opensource repos.
      - name: Install deps
        uses: ./.github/actions/install-deps
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14
      - name: Build deploy test
        uses: ./.github/actions/build-deploy
        with:
          docker_registry: ${{ env.DOCKER_REGISTRY }}
          domain: ${{ env.DOMAIN }}
          k8s_secret_base64: ${{ secrets.SECRET_BASE64 }}
          k8s_config_base64: ${{ secrets.KUBECTL_CONFIG_BASE64 }}
          git_branch: ${{ steps.extract_branch.outputs.branch }}
          context: ${{ env.CONTEXT }}
      - name: Test
        uses: ./.github/actions/postman-health-test
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          DOMAIN: ${{ env.DOMAIN }}
          CONTEXT: ${{ env.CONTEXT }}
    env:
      CONTEXT: dynamic-ns-k8s
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ozone2021
      DOMAIN: oz0n3.com
      DOCKER_REGISTRY: ozone2021